[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.18.2"
lazy-regex = "3.1.0"
regex = "1.10.2"
itertools = "0.12.0"
num = "0.4.1"
cached = "0.47.0"